// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "post_id", Type: field.TypeInt},
		{Name: "type", Type: field.TypeString},
		{Name: "full", Type: field.TypeString},
		{Name: "downloaded_at", Type: field.TypeTime, Nullable: true},
		{Name: "stash_id", Type: field.TypeString},
		{Name: "organized_at", Type: field.TypeTime, Nullable: true},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_posts_medias",
				Columns:    []*schema.Column{MediaColumns[1]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subscription_id", Type: field.TypeInt},
		{Name: "text", Type: field.TypeString},
		{Name: "posted_at", Type: field.TypeString},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// MessageMediaColumns holds the columns for the "message_media" table.
	MessageMediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "message_id", Type: field.TypeInt},
		{Name: "type", Type: field.TypeString},
		{Name: "full", Type: field.TypeString},
		{Name: "downloaded_at", Type: field.TypeTime, Nullable: true},
		{Name: "stash_id", Type: field.TypeString},
		{Name: "organized_at", Type: field.TypeTime, Nullable: true},
	}
	// MessageMediaTable holds the schema information for the "message_media" table.
	MessageMediaTable = &schema.Table{
		Name:       "message_media",
		Columns:    MessageMediaColumns,
		PrimaryKey: []*schema.Column{MessageMediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "message_media_messages_message_media",
				Columns:    []*schema.Column{MessageMediaColumns[1]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subscription_id", Type: field.TypeInt},
		{Name: "text", Type: field.TypeString},
		{Name: "posted_at", Type: field.TypeString},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_subscriptions_posts",
				Columns:    []*schema.Column{PostsColumns[1]},
				RefColumns: []*schema.Column{SubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "avatar", Type: field.TypeString},
		{Name: "header", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "head_marker", Type: field.TypeString},
		{Name: "stash_id", Type: field.TypeString},
		{Name: "organized_at", Type: field.TypeTime, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaTable,
		MessagesTable,
		MessageMediaTable,
		PostsTable,
		SubscriptionsTable,
	}
)

func init() {
	MediaTable.ForeignKeys[0].RefTable = PostsTable
	MessageMediaTable.ForeignKeys[0].RefTable = MessagesTable
	PostsTable.ForeignKeys[0].RefTable = SubscriptionsTable
}
