// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ofdl/ofdl/ent/messagemedia"
	"github.com/ofdl/ofdl/ent/predicate"
)

// MessageMediaDelete is the builder for deleting a MessageMedia entity.
type MessageMediaDelete struct {
	config
	hooks    []Hook
	mutation *MessageMediaMutation
}

// Where appends a list predicates to the MessageMediaDelete builder.
func (mmd *MessageMediaDelete) Where(ps ...predicate.MessageMedia) *MessageMediaDelete {
	mmd.mutation.Where(ps...)
	return mmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mmd *MessageMediaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mmd.sqlExec, mmd.mutation, mmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mmd *MessageMediaDelete) ExecX(ctx context.Context) int {
	n, err := mmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mmd *MessageMediaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messagemedia.Table, sqlgraph.NewFieldSpec(messagemedia.FieldID, field.TypeInt))
	if ps := mmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mmd.mutation.done = true
	return affected, err
}

// MessageMediaDeleteOne is the builder for deleting a single MessageMedia entity.
type MessageMediaDeleteOne struct {
	mmd *MessageMediaDelete
}

// Where appends a list predicates to the MessageMediaDelete builder.
func (mmdo *MessageMediaDeleteOne) Where(ps ...predicate.MessageMedia) *MessageMediaDeleteOne {
	mmdo.mmd.mutation.Where(ps...)
	return mmdo
}

// Exec executes the deletion query.
func (mmdo *MessageMediaDeleteOne) Exec(ctx context.Context) error {
	n, err := mmdo.mmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messagemedia.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mmdo *MessageMediaDeleteOne) ExecX(ctx context.Context) {
	if err := mmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
