// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ofdl/ofdl/ent/message"
	"github.com/ofdl/ofdl/ent/messagemedia"
	"github.com/ofdl/ofdl/ent/predicate"
)

// MessageMediaQuery is the builder for querying MessageMedia entities.
type MessageMediaQuery struct {
	config
	ctx         *QueryContext
	order       []messagemedia.OrderOption
	inters      []Interceptor
	predicates  []predicate.MessageMedia
	withMessage *MessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageMediaQuery builder.
func (mmq *MessageMediaQuery) Where(ps ...predicate.MessageMedia) *MessageMediaQuery {
	mmq.predicates = append(mmq.predicates, ps...)
	return mmq
}

// Limit the number of records to be returned by this query.
func (mmq *MessageMediaQuery) Limit(limit int) *MessageMediaQuery {
	mmq.ctx.Limit = &limit
	return mmq
}

// Offset to start from.
func (mmq *MessageMediaQuery) Offset(offset int) *MessageMediaQuery {
	mmq.ctx.Offset = &offset
	return mmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mmq *MessageMediaQuery) Unique(unique bool) *MessageMediaQuery {
	mmq.ctx.Unique = &unique
	return mmq
}

// Order specifies how the records should be ordered.
func (mmq *MessageMediaQuery) Order(o ...messagemedia.OrderOption) *MessageMediaQuery {
	mmq.order = append(mmq.order, o...)
	return mmq
}

// QueryMessage chains the current query on the "message" edge.
func (mmq *MessageMediaQuery) QueryMessage() *MessageQuery {
	query := (&MessageClient{config: mmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagemedia.Table, messagemedia.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messagemedia.MessageTable, messagemedia.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(mmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MessageMedia entity from the query.
// Returns a *NotFoundError when no MessageMedia was found.
func (mmq *MessageMediaQuery) First(ctx context.Context) (*MessageMedia, error) {
	nodes, err := mmq.Limit(1).All(setContextOp(ctx, mmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messagemedia.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mmq *MessageMediaQuery) FirstX(ctx context.Context) *MessageMedia {
	node, err := mmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageMedia ID from the query.
// Returns a *NotFoundError when no MessageMedia ID was found.
func (mmq *MessageMediaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(1).IDs(setContextOp(ctx, mmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messagemedia.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mmq *MessageMediaQuery) FirstIDX(ctx context.Context) int {
	id, err := mmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageMedia entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageMedia entity is found.
// Returns a *NotFoundError when no MessageMedia entities are found.
func (mmq *MessageMediaQuery) Only(ctx context.Context) (*MessageMedia, error) {
	nodes, err := mmq.Limit(2).All(setContextOp(ctx, mmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messagemedia.Label}
	default:
		return nil, &NotSingularError{messagemedia.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mmq *MessageMediaQuery) OnlyX(ctx context.Context) *MessageMedia {
	node, err := mmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageMedia ID in the query.
// Returns a *NotSingularError when more than one MessageMedia ID is found.
// Returns a *NotFoundError when no entities are found.
func (mmq *MessageMediaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mmq.Limit(2).IDs(setContextOp(ctx, mmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messagemedia.Label}
	default:
		err = &NotSingularError{messagemedia.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mmq *MessageMediaQuery) OnlyIDX(ctx context.Context) int {
	id, err := mmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageMediaSlice.
func (mmq *MessageMediaQuery) All(ctx context.Context) ([]*MessageMedia, error) {
	ctx = setContextOp(ctx, mmq.ctx, "All")
	if err := mmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageMedia, *MessageMediaQuery]()
	return withInterceptors[[]*MessageMedia](ctx, mmq, qr, mmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mmq *MessageMediaQuery) AllX(ctx context.Context) []*MessageMedia {
	nodes, err := mmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageMedia IDs.
func (mmq *MessageMediaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mmq.ctx.Unique == nil && mmq.path != nil {
		mmq.Unique(true)
	}
	ctx = setContextOp(ctx, mmq.ctx, "IDs")
	if err = mmq.Select(messagemedia.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mmq *MessageMediaQuery) IDsX(ctx context.Context) []int {
	ids, err := mmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mmq *MessageMediaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Count")
	if err := mmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mmq, querierCount[*MessageMediaQuery](), mmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mmq *MessageMediaQuery) CountX(ctx context.Context) int {
	count, err := mmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mmq *MessageMediaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mmq.ctx, "Exist")
	switch _, err := mmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mmq *MessageMediaQuery) ExistX(ctx context.Context) bool {
	exist, err := mmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageMediaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mmq *MessageMediaQuery) Clone() *MessageMediaQuery {
	if mmq == nil {
		return nil
	}
	return &MessageMediaQuery{
		config:      mmq.config,
		ctx:         mmq.ctx.Clone(),
		order:       append([]messagemedia.OrderOption{}, mmq.order...),
		inters:      append([]Interceptor{}, mmq.inters...),
		predicates:  append([]predicate.MessageMedia{}, mmq.predicates...),
		withMessage: mmq.withMessage.Clone(),
		// clone intermediate query.
		sql:  mmq.sql.Clone(),
		path: mmq.path,
	}
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (mmq *MessageMediaQuery) WithMessage(opts ...func(*MessageQuery)) *MessageMediaQuery {
	query := (&MessageClient{config: mmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mmq.withMessage = query
	return mmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MessageID int `json:"message_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageMedia.Query().
//		GroupBy(messagemedia.FieldMessageID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mmq *MessageMediaQuery) GroupBy(field string, fields ...string) *MessageMediaGroupBy {
	mmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageMediaGroupBy{build: mmq}
	grbuild.flds = &mmq.ctx.Fields
	grbuild.label = messagemedia.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MessageID int `json:"message_id,omitempty"`
//	}
//
//	client.MessageMedia.Query().
//		Select(messagemedia.FieldMessageID).
//		Scan(ctx, &v)
func (mmq *MessageMediaQuery) Select(fields ...string) *MessageMediaSelect {
	mmq.ctx.Fields = append(mmq.ctx.Fields, fields...)
	sbuild := &MessageMediaSelect{MessageMediaQuery: mmq}
	sbuild.label = messagemedia.Label
	sbuild.flds, sbuild.scan = &mmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageMediaSelect configured with the given aggregations.
func (mmq *MessageMediaQuery) Aggregate(fns ...AggregateFunc) *MessageMediaSelect {
	return mmq.Select().Aggregate(fns...)
}

func (mmq *MessageMediaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mmq); err != nil {
				return err
			}
		}
	}
	for _, f := range mmq.ctx.Fields {
		if !messagemedia.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mmq.path != nil {
		prev, err := mmq.path(ctx)
		if err != nil {
			return err
		}
		mmq.sql = prev
	}
	return nil
}

func (mmq *MessageMediaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageMedia, error) {
	var (
		nodes       = []*MessageMedia{}
		_spec       = mmq.querySpec()
		loadedTypes = [1]bool{
			mmq.withMessage != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageMedia).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageMedia{config: mmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mmq.withMessage; query != nil {
		if err := mmq.loadMessage(ctx, query, nodes, nil,
			func(n *MessageMedia, e *Message) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mmq *MessageMediaQuery) loadMessage(ctx context.Context, query *MessageQuery, nodes []*MessageMedia, init func(*MessageMedia), assign func(*MessageMedia, *Message)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MessageMedia)
	for i := range nodes {
		fk := nodes[i].MessageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(message.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mmq *MessageMediaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mmq.querySpec()
	_spec.Node.Columns = mmq.ctx.Fields
	if len(mmq.ctx.Fields) > 0 {
		_spec.Unique = mmq.ctx.Unique != nil && *mmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mmq.driver, _spec)
}

func (mmq *MessageMediaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messagemedia.Table, messagemedia.Columns, sqlgraph.NewFieldSpec(messagemedia.FieldID, field.TypeInt))
	_spec.From = mmq.sql
	if unique := mmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mmq.path != nil {
		_spec.Unique = true
	}
	if fields := mmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagemedia.FieldID)
		for i := range fields {
			if fields[i] != messagemedia.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mmq.withMessage != nil {
			_spec.Node.AddColumnOnce(messagemedia.FieldMessageID)
		}
	}
	if ps := mmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mmq *MessageMediaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mmq.driver.Dialect())
	t1 := builder.Table(messagemedia.Table)
	columns := mmq.ctx.Fields
	if len(columns) == 0 {
		columns = messagemedia.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mmq.sql != nil {
		selector = mmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mmq.ctx.Unique != nil && *mmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mmq.predicates {
		p(selector)
	}
	for _, p := range mmq.order {
		p(selector)
	}
	if offset := mmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MessageMediaGroupBy is the group-by builder for MessageMedia entities.
type MessageMediaGroupBy struct {
	selector
	build *MessageMediaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mmgb *MessageMediaGroupBy) Aggregate(fns ...AggregateFunc) *MessageMediaGroupBy {
	mmgb.fns = append(mmgb.fns, fns...)
	return mmgb
}

// Scan applies the selector query and scans the result into the given value.
func (mmgb *MessageMediaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mmgb.build.ctx, "GroupBy")
	if err := mmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageMediaQuery, *MessageMediaGroupBy](ctx, mmgb.build, mmgb, mmgb.build.inters, v)
}

func (mmgb *MessageMediaGroupBy) sqlScan(ctx context.Context, root *MessageMediaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mmgb.fns))
	for _, fn := range mmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mmgb.flds)+len(mmgb.fns))
		for _, f := range *mmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageMediaSelect is the builder for selecting fields of MessageMedia entities.
type MessageMediaSelect struct {
	*MessageMediaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mms *MessageMediaSelect) Aggregate(fns ...AggregateFunc) *MessageMediaSelect {
	mms.fns = append(mms.fns, fns...)
	return mms
}

// Scan applies the selector query and scans the result into the given value.
func (mms *MessageMediaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mms.ctx, "Select")
	if err := mms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageMediaQuery, *MessageMediaSelect](ctx, mms.MessageMediaQuery, mms, mms.inters, v)
}

func (mms *MessageMediaSelect) sqlScan(ctx context.Context, root *MessageMediaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mms.fns))
	for _, fn := range mms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
