// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ofdl/ofdl/ent/post"
	"github.com/ofdl/ofdl/ent/subscription"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
}

// SetAvatar sets the "avatar" field.
func (sc *SubscriptionCreate) SetAvatar(s string) *SubscriptionCreate {
	sc.mutation.SetAvatar(s)
	return sc
}

// SetHeader sets the "header" field.
func (sc *SubscriptionCreate) SetHeader(s string) *SubscriptionCreate {
	sc.mutation.SetHeader(s)
	return sc
}

// SetName sets the "name" field.
func (sc *SubscriptionCreate) SetName(s string) *SubscriptionCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetUsername sets the "username" field.
func (sc *SubscriptionCreate) SetUsername(s string) *SubscriptionCreate {
	sc.mutation.SetUsername(s)
	return sc
}

// SetHeadMarker sets the "head_marker" field.
func (sc *SubscriptionCreate) SetHeadMarker(s string) *SubscriptionCreate {
	sc.mutation.SetHeadMarker(s)
	return sc
}

// SetStashID sets the "stash_id" field.
func (sc *SubscriptionCreate) SetStashID(s string) *SubscriptionCreate {
	sc.mutation.SetStashID(s)
	return sc
}

// SetOrganizedAt sets the "organized_at" field.
func (sc *SubscriptionCreate) SetOrganizedAt(t time.Time) *SubscriptionCreate {
	sc.mutation.SetOrganizedAt(t)
	return sc
}

// SetNillableOrganizedAt sets the "organized_at" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableOrganizedAt(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetOrganizedAt(*t)
	}
	return sc
}

// SetEnabled sets the "enabled" field.
func (sc *SubscriptionCreate) SetEnabled(b bool) *SubscriptionCreate {
	sc.mutation.SetEnabled(b)
	return sc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableEnabled(b *bool) *SubscriptionCreate {
	if b != nil {
		sc.SetEnabled(*b)
	}
	return sc
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (sc *SubscriptionCreate) AddPostIDs(ids ...int) *SubscriptionCreate {
	sc.mutation.AddPostIDs(ids...)
	return sc
}

// AddPosts adds the "posts" edges to the Post entity.
func (sc *SubscriptionCreate) AddPosts(p ...*Post) *SubscriptionCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPostIDs(ids...)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (sc *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return sc.mutation
}

// Save creates the Subscription in the database.
func (sc *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SubscriptionCreate) defaults() {
	if _, ok := sc.mutation.Enabled(); !ok {
		v := subscription.DefaultEnabled
		sc.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubscriptionCreate) check() error {
	if _, ok := sc.mutation.Avatar(); !ok {
		return &ValidationError{Name: "avatar", err: errors.New(`ent: missing required field "Subscription.avatar"`)}
	}
	if _, ok := sc.mutation.Header(); !ok {
		return &ValidationError{Name: "header", err: errors.New(`ent: missing required field "Subscription.header"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Subscription.name"`)}
	}
	if _, ok := sc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Subscription.username"`)}
	}
	if _, ok := sc.mutation.HeadMarker(); !ok {
		return &ValidationError{Name: "head_marker", err: errors.New(`ent: missing required field "Subscription.head_marker"`)}
	}
	if _, ok := sc.mutation.StashID(); !ok {
		return &ValidationError{Name: "stash_id", err: errors.New(`ent: missing required field "Subscription.stash_id"`)}
	}
	if _, ok := sc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Subscription.enabled"`)}
	}
	return nil
}

func (sc *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Avatar(); ok {
		_spec.SetField(subscription.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := sc.mutation.Header(); ok {
		_spec.SetField(subscription.FieldHeader, field.TypeString, value)
		_node.Header = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(subscription.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Username(); ok {
		_spec.SetField(subscription.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := sc.mutation.HeadMarker(); ok {
		_spec.SetField(subscription.FieldHeadMarker, field.TypeString, value)
		_node.HeadMarker = value
	}
	if value, ok := sc.mutation.StashID(); ok {
		_spec.SetField(subscription.FieldStashID, field.TypeString, value)
		_node.StashID = value
	}
	if value, ok := sc.mutation.OrganizedAt(); ok {
		_spec.SetField(subscription.FieldOrganizedAt, field.TypeTime, value)
		_node.OrganizedAt = value
	}
	if value, ok := sc.mutation.Enabled(); ok {
		_spec.SetField(subscription.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := sc.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PostsTable,
			Columns: []string{subscription.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	builders []*SubscriptionCreate
}

// Save creates the Subscription entities in the database.
func (scb *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subscription, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
